#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nload
Version  : 8f92dc04fad283abdd2a4538cd4c2093d957d9da
Release  : 1
URL      : https://github.com/rolandriegel/nload/archive/8f92dc04fad283abdd2a4538cd4c2093d957d9da.tar.gz
Source0  : https://github.com/rolandriegel/nload/archive/8f92dc04fad283abdd2a4538cd4c2093d957d9da.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: nload-bin = %{version}-%{release}
Requires: nload-license = %{version}-%{release}
Requires: nload-man = %{version}-%{release}
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)

%description
# nload
**Real time network traffic monitor for the text console**
![](http://www.roland-riegel.de/nload/screenshots/shot1.png)

%package bin
Summary: bin components for the nload package.
Group: Binaries
Requires: nload-license = %{version}-%{release}
Requires: nload-man = %{version}-%{release}

%description bin
bin components for the nload package.


%package license
Summary: license components for the nload package.
Group: Default

%description license
license components for the nload package.


%package man
Summary: man components for the nload package.
Group: Default

%description man
man components for the nload package.


%prep
%setup -q -n nload-8f92dc04fad283abdd2a4538cd4c2093d957d9da

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1545958432
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1545958432
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nload
cp COPYING %{buildroot}/usr/share/package-licenses/nload/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/nload

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nload/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/nload.1.gz
